name: Web App Packaging test

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint 

      - name: Run tests
        run: npm test

      - name: Start the React application
        run: |
          npm start &
          sleep 10 # Attendez que le serveur démarre
          curl -f http://localhost:3000 || exit 1 # Remplacez par l'URL où votre app démarre

      - name: Stop React application
        if: success()
        run: pkill -f "npm start"
